# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  # Enable high-level summary of changes
  high_level_summary: true
  # Enable poem in the summary (fun touch)
  poem: true
  # Review status to post
  review_status: true
  # Collapse walkthrough in the summary
  collapse_walkthrough: false
  # Path-based review instructions
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        Review TypeScript code for:
        - Type safety and proper use of TypeScript features
        - Consistent naming conventions
        - Proper error handling
        - Performance considerations for SVG generation
    - path: "**/*.yml"
      instructions: |
        Review GitHub Actions workflows for:
        - Security best practices
        - Proper permissions
        - Efficient caching strategies

chat:
  # Enable auto-reply for chat messages
  auto_reply: true

# Enable early access features
early_access: true
